# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"6\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\"G\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x03 \x01(\x08\"E\n\nVoteReport\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x03 \x01(\x08\"K\n\x0f\x44\x65\x63isionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12 \n\x05votes\x18\x02 \x03(\x0b\x32\x11.twopc.VoteReport\"@\n\x0f\x44\x65\x63isionMessage\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x15\n\rglobal_commit\x18\x02 \x01(\x08\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\rVotingService\x12/\n\x04Vote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponse2L\n\x12\x43oordinatorService\x12\x36\n\x0bRequestVote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponse2x\n\x0f\x44\x65\x63isionService\x12+\n\nReportVote\x12\x11.twopc.VoteReport\x1a\n.twopc.Ack\x12\x38\n\x12StartDecisionPhase\x12\x16.twopc.DecisionRequest\x1a\n.twopc.Ack2M\n\x15GlobalDecisionService\x12\x34\n\x0eGlobalDecision\x12\x16.twopc.DecisionMessage\x1a\n.twopc.AckB\x13Z\x11twopc/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021twopc/proto;proto'
  _globals['_VOTEREQUEST']._serialized_start=22
  _globals['_VOTEREQUEST']._serialized_end=76
  _globals['_VOTERESPONSE']._serialized_start=78
  _globals['_VOTERESPONSE']._serialized_end=149
  _globals['_VOTEREPORT']._serialized_start=151
  _globals['_VOTEREPORT']._serialized_end=220
  _globals['_DECISIONREQUEST']._serialized_start=222
  _globals['_DECISIONREQUEST']._serialized_end=297
  _globals['_DECISIONMESSAGE']._serialized_start=299
  _globals['_DECISIONMESSAGE']._serialized_end=363
  _globals['_ACK']._serialized_start=365
  _globals['_ACK']._serialized_end=387
  _globals['_VOTINGSERVICE']._serialized_start=389
  _globals['_VOTINGSERVICE']._serialized_end=453
  _globals['_COORDINATORSERVICE']._serialized_start=455
  _globals['_COORDINATORSERVICE']._serialized_end=531
  _globals['_DECISIONSERVICE']._serialized_start=533
  _globals['_DECISIONSERVICE']._serialized_end=653
  _globals['_GLOBALDECISIONSERVICE']._serialized_start=655
  _globals['_GLOBALDECISIONSERVICE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
